spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:


  profiles:
    include: oauth

  data:
    redis:
      host: 3.36.93.73
      port: 6379


  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 163906202850-vovn9m47at6ste2k3bf15g155prjisot.apps.googleusercontent.com
            clientSecret: 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
            scope: profile,email

          kakao:
            client-id: 8c70ca1b49ada3a6a00aafdf2b0f125a
            redirect-uri: "http://localhost:8080/kakao/login"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret:
    key: EGHGKK2959wkOTntmZTsnbT309299nYTr20djhJODJOnpA==

file:
  dir: C:\Users\zxc78\Documents\game_matching_service\matchingService\src\main\resources\static\files



jda:
  discord:
    key: MTA3MzU4MzEzNzI4NTc0MjU5Mw.G4Gu4I.-oiQr-6RFg4SXqtbD7gyiaBPq1wWlpmTxcwrXg
    guild:
      id: 1073444544852541500
      category:
        Egid: 1073498877904298036
        Hgid: 1074496423837569106

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: game-matching
    stack:
      auto: false
    credentials:
      secret-key: 0qO40kZP+Ad/yICcxM1dSqL3QxpQ4IMLQZIKZkYs
      access-key: AKIA3NXTMDKZ37HSL53M

